### ISSUE TITLE
[FEAT] 장바구니가 비어있는 경우 대응

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-banchan-07#94]
## Screen Type
- 장바구니

## Description
- 장바구니가 비어있는 경우 다르게 화면을 표시한다.

## Task
- [x] 빈 리스트를 보여줄 뷰홀더 생성

**Comment by 2004yyj** [comment]
비어있는 경우엔 뷰홀더를 추가하지 말고 그냥 fragment에서 처리하는 것은 어떨까요?

**Comment by 2004yyj** [comment]
물론 뷰 만들어주시는건 좋을 것 같슴다

**Comment by oreocube** [comment]
장바구니 화면 하단에 최근 본 상품도 있어서 그건 어렵지 않을까요?
